### ISSUE TITLE
Adatbázis kapcsolat kialakítása

### ISSUE THREAD

**Issue by Luxeonn** [BoozePal/BoozePal#16]
Legyen egy db. Szükséges a #9 issue megvalósításához.

**Comment by nandorholozsnyak** [comment]
Elsősorban szerintem egy H2 in memory db elég lesz, később a cloudon kitelepül egy MySQL szerver amit majd tudunk használni.

**Comment by nandorholozsnyak** [comment]
@Luxeonn olvasd el a pull requestben szereplő leírást :)
