### ISSUE TITLE
Bejelentkezés api

### ISSUE THREAD

**Issue by Luxeonn** [BoozePal/BoozePal#25]
Elérhetőség: POST /rest/user/login
Felhasználó megadja az adatiat. Bejövő adatok: felhasználónév, jelszó Válasz: Sikeres authentikáció után a felhasználó entitása, sikertelennél üres felhasználó.

**Comment by nandorholozsnyak** [comment]
Az android kliensen való bejelentkezés egy tokent dolgozunk fel amiben megkapjuk a felhasználó adatait amit perzisztálunk.

**Comment by nandorholozsnyak** [comment]
Kisebb változás.
Bejövő adat: A Google API token.
Válasz: Ha sikeres a bejelentkezés, azaz valid a token akkor a felhasználó entitás (vagy új vagy egy már létező), ha nem valid a token akkor NULL.
