### ISSUE TITLE
Cimbora keresés api

### ISSUE THREAD

**Issue by Luxeonn** [BoozePal/BoozePal#27]
Elérhetőség: POST /rest/user/pal
Felhasználó a megnyitja a "Cimbora lapot" és ott megnyom egy gombot amire megjelenítődik a közeleben lévő cimborák. Bejövő adatok: Felhasználó id, GPS koordináták. Válasz: Közelben lévő felhasználók listája.

**Comment by nandorholozsnyak** [comment]
#38-as issueban ez megvalósult csak nem felhasználó id kell hanem token.

**Comment by nandorholozsnyak** [comment]
Elérhetősége legyen: /rest/user/findPals

Kapott adatok: token és user.
Visszaadot adatok: az adott felhasználó sugarán belül lévő felhasználók.

**Comment by nandorholozsnyak** [comment]
@fannymonori elkészült az endpoint és amikor küldöd a kérést akkor megtörténik az aktuális pozíció frissítése is. Szólj ha minden okés.
