### ISSUE TITLE
Spring Security konfigurálása

### ISSUE THREAD

**Issue by nandorholozsnyak** [BoozePal/BoozePal#3]
Spring Security függőség felvétele és annak konfigurációja xml vagy java alapon.

**Comment by Holi60k** [comment]
Spring Security függőség felvétele és annak konfigurációja xml vagy java alapon.

**Comment by Luxeonn** [comment]
Első körben xml alapú konfig lesz. De hétvégére átnézem a java alapú megvalósítást és később refraktornál át lehet vezetni.

**Comment by Luxeonn** [comment]
5h
