### ISSUE TITLE
REST kijelentkeztetés

### ISSUE THREAD

**Issue by nandorholozsnyak** [BoozePal/BoozePal#43]
Android kliensnek REST-es végpont a kijelentkeztetésre.
PATH:/user/logout - paraméterek: Token

**Comment by Luxeonn** [comment]
@fannymonori  
/rest/user/logout és egy tokent várunk csak, az elegendő az authentikációhoz és a kijelentkeztetéshez. 
Fent van teszten, lehet tesztelni.

**Comment by fannymonori** [comment]
@Luxeonn 
Készen, kipróbáltam, visszakaptam hogy OK. Ha az alkalmazás a háttérbe kerül akkor küldi.
