### ISSUE TITLE
Ráérési napok fogadása

### ISSUE THREAD

**Issue by nandorholozsnyak** [BoozePal/BoozePal#45]
Az android kliensen való naptári napok kijelölése utána a "ráérési napok" átkerülnek a szerverre és ott az adott felhasználóhoz rendeli.
Ehhez kell biztosítani egy endpointot.
PATH: /user/timetable
Fogadott adatok:
-Token
-Lista ami tartalmazza a napokat. (java.util.Date)

Válasz:
HTTP OK

**Comment by Luxeonn** [comment]
@fannymonori 
Fent van master-ben a ráérési napok fogadása, lehet tesztelni.
