### ISSUE TITLE
Térképen a legkedveltebb pontok megjelenítése.

### ISSUE THREAD

**Issue by nandorholozsnyak** [BoozePal/BoozePal#52]
A Google maps api képes adatokat vizualizálni:
https://developers.google.com/maps/documentation/javascript/earthquakes

Ez alapján lehetne készíteni egy ilyen funkciót ami az adminoknak ad infót a legkedveltebb helyekről, azaz ahová a legtöbben járnak.

**Comment by Luxeonn** [comment]
:D

**Comment by nandorholozsnyak** [comment]
Lezárom mert úgyse lesz már kész :D Majd a vadi újban :D
