### ISSUE TITLE
Admin oldalon kijelentkeztetés adatbázisból logikailag.

### ISSUE THREAD

**Issue by nandorholozsnyak** [BoozePal/BoozePal#55]
Az admin oldalon való kijelentkeztetésnél meg kell oldani, hogy az adatbázisba is leíródjon a kijelentkezés azaz biztosítani kell egy Logout Filter-t vagy egy LogoutSuccesHandlert ami utána a User-t logikailag is kilépteti.

**Comment by nandorholozsnyak** [comment]
@Luxeonn rád raktam mer tudom hogy volt az utóbbi időben kapcsolatod Logout Filterrel :)

**Comment by Luxeonn** [comment]
oksa
