### ISSUE TITLE
Felhasználó teljeskörű adatai megjelenítése

### ISSUE THREAD

**Issue by nandorholozsnyak** [BoozePal/BoozePal#56]
A  felhasználók listázása menüpont alatt a táblázatban a felsorolt felhasználók adatait tudjuk megjeleníteni, ahogy rákattintunk a felhasználóra alatta vagy egy felugró ablakban írjuk ki minden adatát.

**Comment by nandorholozsnyak** [comment]
@Luxeonn a felhasználók listázása részt Te csináltad, lehet ez is tetszeni fog akkor még mint új funckió mellé.

**Comment by Luxeonn** [comment]
sima :)
