### ISSUE TITLE
Cimbora kiválasztása

### ISSUE THREAD

**Issue by fannymonori** [BoozePal/BoozePal#70]
A közelben lévő elérhető cimborák közül egyet kiválaszt a felhasználó, majd kiválasztja annak egy ráérő napját. Ekkor küld egy requestet a kiválasztott felhasználónak hogy szeretne vele inni aznap. A másik felhasználó azt a kérést majd el tudja utasítani/fogadni.
elérhetőség: /rest/user/sendrequest
kliens küldi: bejelentkezett user+token, kiválasztott user, időpont
válasz: OK/nem OK

**Comment by nandorholozsnyak** [comment]
Kliens küldi: Token, Kiválszatott user id, időpont.

**Comment by nandorholozsnyak** [comment]
@fannymonori Úgy változott az egész hogy a következő adatokat várjuk.

```
 /**
     * Felhasználó ID-ja.
     */
    private Long userId;

    /**
     * A megjelöltnek jelölt ID;
     */
    private Long requestedUserId;

    /**
     * A megjelölt dátum.
     */
    private Date date;
    
    /**
     * Kocsma azonosítója.
     */
    private Long pubId;
```
Ha valami nem egyértelmű szólj, nemsokára megy ki a tesztre és lehet tesztelni.

**Comment by nandorholozsnyak** [comment]
@fannymonori amikor megfogod hívni a getUser végpontot akkor amikor visszakapod a felhasználót az actualPals mező a következőképpen néz majd ki, így dolgozz vele tovább, vagyis nálunk az entitásban így néz ki, nem tudom hogy nálad végül ez hogyan fog transzformálódni.

`private Map<User, PalRequest> actualPals;`
ahol a PalRequest
```
private Pub pub;
private Date date;
```

**Comment by nandorholozsnyak** [comment]
@fannymonori ez zárható akkor? :)

**Comment by fannymonori** [comment]
@Holi60k igen :)
