### ISSUE TITLE
Cimbora elfogadás-elutasítás

### ISSUE THREAD

**Issue by fannymonori** [BoozePal/BoozePal#71]
A felhasználót kiválasztotta valaki, hogy egy adott napon szeretni inni. Akinek jött a kérés, az elfogadhatja, és akkor kerülnek be egymás saját cimborái közé, vagy elutasíthatja.
elérhetőség: /rest/user/acceptrequest, /rest/user/denyrequest
kliens küldi: bejelentkezett user+token, a kérő use, időpont, és egy bool érték hogy elfogadja vagy elutasítja. @Holi60k így jó lesz?
válasz: OK

**Comment by nandorholozsnyak** [comment]
Kliens küldi: Felhasználó tokene, Kérő user id, bool érték.

**Comment by nandorholozsnyak** [comment]
Kliens küldi: Felhasználó Id, Kért user Id, bool érték.

**Comment by nandorholozsnyak** [comment]
@fannymonori  amint lemegy a merge és deployol a következő címen éred el:
/rest/user/acceptrequest

Amit vár az egy VO:

```
/**
     * Felhasználó ID-ja.
     */
    private Long userId;

    /**
     * A megjelöltnek jelölt ID;
     */
    private Long requestedUserId;

    /**
     * Elfogadott állapota.
     */
    private boolean accepted;
```

userId aki éppen bejelentkezve van, a requestedUser aki a felkérést kldte az accepted pedig az állapota. :)

**Comment by nandorholozsnyak** [comment]
@fannymonori illetve ez is akkor? :D

**Comment by fannymonori** [comment]
@Holi60k ez is :D
