### ISSUE TITLE
getUser endpoint

### ISSUE THREAD

**Issue by fannymonori** [BoozePal/BoozePal#72]
Egy endpoint ahol a bejelentkezett felhasználó adatait ellehet kérni frissítés céljából.
/rest/user/getuser
kliens küldi: @Holi60k @Luxeonn token+user jó lesz?
válasz: user entitás

**Comment by nandorholozsnyak** [comment]
@fannymonori amint kimegy tesztelhető is.
/boozepal/rest/user/getUser/{token} egy GET-es hívás mehet erre.

**Comment by fannymonori** [comment]
@Holi60k működik :)

**Comment by nandorholozsnyak** [comment]
@fannymonori rendben van zárom.
