### ISSUE TITLE
Base template elkészítése a felülethez.

### ISSUE THREAD

**Issue by nandorholozsnyak** [BoozePal/BoozePal#8]
Egy olyan felület elkészítése amely egy alapot ad majd a későbbiekben a weblaphoz.

**Comment by Luxeonn** [comment]
a #4 issue alá tartozik. Egybe veszem őket.

**Comment by Luxeonn** [comment]
Kedden átbeszéljük, hogyan is nézzen ki pontosan. Most még csak egy alap állapotba hoztam. Semmi extra nincs benne.

**Comment by Luxeonn** [comment]
1h
