### ISSUE TITLE
Kocsmák feltöltése

### ISSUE THREAD

**Issue by Luxeonn** [BoozePal/BoozePal#85]
Fel kell venni egy pár kocsmát startupBean  vagy ha megoldható akkor liquibase.

**Comment by nandorholozsnyak** [comment]
@Luxeonn ezzel végül mi lesz a megoldás? Liquibase vagy a bean? :)

**Comment by Luxeonn** [comment]
Idő hiány miatt bean, mert nem tudom mennyi idő lenne a liquibase-t belőni.
