### ISSUE TITLE
Bejelentkezés és kijelentkezés megvalósítása.

### ISSUE THREAD

**Issue by nandorholozsnyak** [BoozePal/BoozePal#9]
Bejelentkezéshez felület illetve a szükséges servicek elkészítése.

**Comment by Luxeonn** [comment]
Db szükséges. Most mockolt adatokkal tudunk bejelentkezni 
Jelszó "alma"

**Comment by Luxeonn** [comment]
Illetve a kijelentkezés is működik!

**Comment by Luxeonn** [comment]
kapcsolódó issue #16 #7
